In [2]:
import pandas as pd
import csv

In [ ]:
# 1. Leer CSV original
# =========================
df = pd.read_csv("../data/diputados_original_hcdn.csv")
# =========================

In [ ]:
# 2. Limpiar nombres de columnas
# =========================
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
)

# Ahora las columnas quedan:
# id, apellido, nombre, genero, distrito, inicio, fin,
# juramento, cese, bloque, bloque_inicio, bloque_fin

In [ ]:
# 3. Limpiar textos y pasar todo a minúscula
# =========================

columnas_texto = df.select_dtypes(include="object").columns

for col in columnas_texto:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )

# Reemplazar strings raros de nulos
df = df.replace({
    "nan": pd.NA,
    "none": pd.NA,
    "nat": pd.NA,
    "": pd.NA
})

In [17]:
# 4. Convertir fechas y sacar horarios
# =========================

columnas_fecha = [
    "inicio",
    "fin",
    "juramento",
    "cese",
    "bloque_inicio",
    "bloque_fin"
]

for col in columnas_fecha:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [ ]:
# 5. Crear CSV histórico limpio
# =========================

df_historial = df.copy()

# Para guardar sin horario
for col in columnas_fecha:
    df_historial[col] = df_historial[col].dt.strftime("%Y-%m-%d")
df_historial.to_csv(
    "../data/diputados_historial_limpio.csv",
    index=False,
    quoting=csv.QUOTE_NONE,
    escapechar="\\"
)

In [23]:
# =========================
# 6. Crear CSV sin diputados repetidos
# =========================

df_unicos = (
    df
    .groupby("id", as_index=False)
    .agg(
        nombre=("nombre", "first"),
        apellido=("apellido", "first"),
        genero=("genero", "first"),
        distritos=("distrito", lambda x: " | ".join(sorted(x.dropna().unique()))),
        cantidad_distritos=("distrito", "nunique"),
        cantidad_bloques=("bloque", "nunique"),
        fecha_inicio=("inicio", "min"),
        fecha_fin=("fin", "max")
    )
)

df_unicos = df_unicos.rename(columns={
    "id": "id_diputado"
})

df_unicos["nombre_completo"] = (
    df_unicos["nombre"].str.strip() + " " + df_unicos["apellido"].str.strip()
)

df_unicos = df_unicos[
    [
        "id_diputado",
        "nombre",
        "apellido",
        "nombre_completo",
        "genero",
        "distritos",
        "cantidad_distritos",
        "cantidad_bloques",
        "fecha_inicio",
        "fecha_fin"
    ]
]

df_unicos["fecha_inicio"] = df_unicos["fecha_inicio"].dt.strftime("%Y-%m-%d")
df_unicos["fecha_fin"] = df_unicos["fecha_fin"].dt.strftime("%Y-%m-%d")

df_unicos.to_csv(
    "../data/diputados_unicos.csv",
    index=False
)

df_unicos.head()

,id_diputado,nombre,apellido,nombre_completo,genero,distritos,cantidad_distritos,cantidad_bloques,fecha_inicio,fecha_fin
0,hcdn0011,dulce,granados,dulce granados,f,buenos aires,1,1,2009-12-10,2017-12-09
1,hcdn0014,marcelo eduardo,lopez arias,marcelo eduardo lopez arias,m,salta,1,3,2007-12-10,2011-12-09
2,hcdn0019,mabel hilda,müller,mabel hilda müller,f,buenos aires,1,2,2009-12-10,2013-12-09
3,hcdn0022,miguel angel,pichetto,miguel angel pichetto,m,buenos aires,1,3,2023-12-10,2027-12-09
4,hcdn0035,mario raul,negri,mario raul negri,m,cordoba,1,1,2011-12-10,2023-12-09

In [18]:
df.head()

,id,apellido,nombre,genero,distrito,inicio,fin,juramento,cese,bloque,bloque_inicio,bloque_fin
0,hcdn1136,abdala de matarazzo,norma amanda,f,santiago del estero,2009-12-10,2013-12-09,2009-12-03,2013-12-09,frente civico por santiago,2009-12-10,2013-12-09
1,hcdn1136,abdala de matarazzo,norma amanda,f,santiago del estero,2013-12-10,2017-12-09,2013-12-04,2017-12-09,frente civico por santiago,2013-12-10,2017-12-09
2,hcdn1136,abdala de matarazzo,norma amanda,f,santiago del estero,2017-12-10,2021-12-09,2017-12-06,2021-12-09,frente civico por santiago,2017-12-10,2019-12-09
3,hcdn1136,abdala de matarazzo,norma amanda,f,santiago del estero,2017-12-10,2021-12-09,2017-12-06,2021-12-09,frente de todos,2019-12-10,2021-12-09
4,hcdn1382,abraham,alejandro,m,mendoza,2013-12-10,2017-12-09,2013-12-04,2017-12-09,frente para la victoria - pj,2013-12-13,2017-12-09

In [7]:
df = pd.read_csv(r'C:\Users\Saroka\Downloads\diputados1.6.csv')

In [8]:
df.head()

,ID,APELLIDO,NOMBRE,GENERO,DISTRITO,INICIO,FIN,JURAMENTO,CESE,BLOQUE,BLOQUE_INICIO,BLOQUE_FIN
0,HCDN1136,ABDALA DE MATARAZZO,NORMA AMANDA,F,SANTIAGO DEL ESTERO,2009-12-10T00:00:00,2013-12-09T00:00:00,2009-12-03T00:00:00,2013-12-09T00:00:00,FRENTE CIVICO POR SANTIAGO,2009-12-10T00:00:00,2013-12-09T00:00:00
1,HCDN1136,ABDALA DE MATARAZZO,NORMA AMANDA,F,SANTIAGO DEL ESTERO,2013-12-10T00:00:00,2017-12-09T00:00:00,2013-12-04T00:00:00,2017-12-09T00:00:00,FRENTE CIVICO POR SANTIAGO,2013-12-10T00:00:00,2017-12-09T00:00:00
2,HCDN1136,ABDALA DE MATARAZZO,NORMA AMANDA,F,SANTIAGO DEL ESTERO,2017-12-10T00:00:00,2021-12-09T00:00:00,2017-12-06T00:00:00,2021-12-09T00:00:00,FRENTE CIVICO POR SANTIAGO,2017-12-10T00:00:00,2019-12-09T00:00:00
3,HCDN1136,ABDALA DE MATARAZZO,NORMA AMANDA,F,SANTIAGO DEL ESTERO,2017-12-10T00:00:00,2021-12-09T00:00:00,2017-12-06T00:00:00,2021-12-09T00:00:00,FRENTE DE TODOS,2019-12-10T00:00:00,2021-12-09T00:00:00
4,HCDN1382,ABRAHAM,ALEJANDRO,M,MENDOZA,2013-12-10T00:00:00,2017-12-09T00:00:00,2013-12-04T00:00:00,2017-12-09T00:00:00,FRENTE PARA LA VICTORIA - PJ,2013-12-13T00:00:00,2017-12-09T00:00:00

In [9]:
df['INICIO'].min()

'2007-12-10T00:00:00'